### ISSUE TITLE
Error downloading Repo

### ISSUE THREAD

**Issue by dan-drk** [luismurao/ntbox#10]
Hi. 
Hello.
I'm trying to install the ntbox package and it throws me this error:
>devtools::install_github(´luismurao/ntbox´)
Downloading GitHub repo luismurao/ntbox@HEAD
Error in utils::download.file(url, path, method = method, quite = quite, : download from ´https://api.github.com/repos/luismurao/ntbox/tarball/HEAD´ failed

I´m working un a macBocok Pro         R 4.10.       RStudio 1.4.1106

**Comment by luismurao** [comment]
Hello @dan-drk,
Try using
remotes::install_github("luismurao/ntbox")

**Comment by dan-drk** [comment]
Hello again. 
Tried that several times yesterday, and nothing happened.
Frustrated and tired, I turned off the computer and ran the script again today and it worked perfectly.
Anyway, thank you very much !!! Great job!

**Comment by luismurao** [comment]
Perfect! Thank you. I will close this issue since thee is no problem.
Luis
