### ISSUE TITLE
Raster layer name is not showing correctly when running ntbox GUI ver 0.6.6.5

### ISSUE THREAD

**Issue by yucheols** [luismurao/ntbox#15]
Hello,
I've been using ntbox for a couple of years now, and this is a really nice pacakge! So first off, thank you for making this great package available.

I recently ran into a minor issue when running ntbox GUI ver 0.6.6.5. I've recently re-installed ntbox after updating R. And this issue came up after re-installing the package.

After loading my raster layers of environmental variables into the GUI and extracting niche data, 
the column headers are written as "layer.1, layer.2, layer.3,......" instead of showing the actual layer names, i.e. bio1, bio2, bio3,.......

The environmental data layers I used were the WorldClim bioclimatic variables at 2.5 arcmin resolution. I downloaded the layers through the "getData" function of the raster package and cropped the layers & exported them to my working directory.
This is my routine process of preparing raster layers for niche modeling, and I've never encountered this issue before. So this is pretty confusing. I've attached a screenshot of ntbox GUI with weird column headers.

Just to be clear, the layers are all named correctly: the layers were saved as bio1, bio2, bio3,.... instead of layer.1, layer2... and so on. 

Thank you in advance for your time and help!
All the best,
Yucheol

 
![Screenshot_2023-02-17-17-01-25](https://user-images.githubusercontent.com/85914125/219588316-93965125-4929-4f67-b873-c9fad3573b6e.png)

**Comment by luismurao** [comment]
Hello @yucheols 
Thanks for reporting this issue I think it is fixed. Please install the new version of ntbox and let me know if it worked.
Best,
Luis

**Comment by yucheols** [comment]
Hello Luis,
Thanks for the quick response! I reinstalled the package and the issue is solved :)
Thank you very much!

Cheers,
Yucheol

**Comment by luismurao** [comment]
Excelent! I am closing this issue
