### ISSUE TITLE
problem in the Ellipsoid model

### ISSUE THREAD

**Issue by PabloCurrichi** [luismurao/ntbox#17]
i have a problem in the ellipsoid model part when selecting the funcion Run analysis it gives me a warning: Error in: cannot allocate vector of size 3.5 Gb How can i solve that?

**Comment by luismurao** [comment]
Hello @PabloCurrichi, unfortunately it seems that the problem is that your computer might not have enough memory, so the solution would be to use another with more memory.

**Comment by luismurao** [comment]
The issue is related with users computer memory
