### ISSUE TITLE
‘rgeos’, ‘rgdal’ Paquetes que fueron archivados

### ISSUE THREAD

**Issue by GerardoGuel** [luismurao/ntbox#19]
Hola, recientemente en octubre archivaron estos paquetes los cuales formaban parte de Ntbox, y no me deja ejecutar la paquetería, hay alguna manera de arreglar esto? O esperar a que los desarchiven.

**Comment by luismurao** [comment]
Hola @GerardoGuel,
Parece que ya quedó, por favor intenta instalar de nuevo.

**Comment by GerardoGuel** [comment]
> Hola @GerardoGuel, Parece que ya quedó, por favor intenta instalar de nuevo.

Funciono, gracias !! 

![image](https://github.com/luismurao/ntbox/assets/149863560/a123d599-50af-4a50-a9db-fb9058785507)
