### ISSUE TITLE
Problems with plotting the ecological space

### ISSUE THREAD

**Issue by CescGV** [luismurao/ntbox#2]
Hola, 

Estoy siguiendo el curso de ENM2020 y me interesa mucho tu aplicación! Me la he descargado con R, he cargado los datos de mi proyecto, y todo parece funcionar excepto una cosa: No me aparece el espacio de nicho ecológico; no me aparece gráficamente: 

Loading the data is not an issue since I can load the predictor variables and I can see them on the map when I load it. Also, the maps have the same coordinate system, extension and resolution
![Capture](https://user-images.githubusercontent.com/63144424/78424311-0411a700-766d-11ea-9241-08b89b3d0aa2.PNG)
![capture2](https://user-images.githubusercontent.com/63144424/78424314-06740100-766d-11ea-9931-bc115ad83818.PNG)

Do you have any idea why this could be?

Thank you very much,

Cesc

**Comment by luismurao** [comment]
Hi Cesc,
Check your version of RStudio. Previous versions would no display WebGL plots (the one that ntbox uses to plot 3D E-space).  On the other hand, you can use the button **Open in Browser** that is located in the top-left corner or just copy the web address also there to Chrome or Mozilla
Best regards,
Luis

**Comment by myces** [comment]
Hi, I´m having this problem :-( 
 Erro: Failed to install 'ntbox' from GitHub:
  (convertido do aviso) package ‘car’ is not available (for R version 3.4.1)
do I have to install a previous version?  Thanks!

**Comment by luismurao** [comment]
@myces 

The error means the car package which is a package imported by nichetoolbox is not available for your R version (3.4.1), you should update your R. I recommend you install the version 3.6 and also  RTools. 
All the best
Luis
