### ISSUE TITLE
Cant install ntbox GUI

### ISSUE THREAD

**Issue by Anil-2009** [luismurao/ntbox#3]
I have been trying to install ntbox following instruction already install R tools (msi), I have 3.6.1 R version. Following message popped up 
Error: Failed to install 'ntbox' from GitHub:
  (converted from warning) dependency ‘mnormt’ is not available

How can I address this, many thanks in advance. 

Best
Anil

**Comment by luismurao** [comment]
Dear @Anil-2009,

The problem relates to the fact that the new version of the package "mnormt" has been designed to work just in R version >= 4.0. On the other hand, there are two possible solutions and you can choose what is best for you. The first is to upgrade R to version 4 that will have the advantage that probably you won't have this kind of version-related issues in the future. The second, solution is to install an older version of the "mnormt" package following the next steps:

    1) Close all your R sessions and start a new one
    2) install.packages("https://cran.r-project.org/src/contrib/Archive/mnormt/mnormt_1.5-6.tar.gz", repos=NULL,type="source")
install.packages("devtools") #if it asks to update packages do not do it, use option 3
    3) devtools::install_github("luismurao/ntbox") #if it asks to update packages do not do it, use option 3

Please do not hesitate to contact me if you still having problems
Best regards,
Luis

**Comment by Anil-2009** [comment]
Thank you so much for your quick response, really appreciated. I followed your instructions but again failed, following error message popped up

package ‘rlang’ successfully unpacked and MD5 sums checked
Error: Failed to install 'ntbox' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘rlang’

Thanks so much for your help.

Best
Anil


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by Anil-2009** [comment]
Dear Luis,
I managed to solve the issues, will use it and let you know my experience. Thanks.

Best
Anil


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by luismurao** [comment]
Great @Anil-2009 ! 
I am closing the issue as it is already solved. 

Just one more thing make sure that you have installed pandoc. If you are using windows you can install it using the intallr package as follows:

install.packages("installr")
library(installr)
# Installing pandoc
install.pandoc()
Best,
Luis

**Comment by GuguYanez** [comment]
Hi! I have the same second problem of @Anil-2009 

I follow all the steps and get:

Error: Failed to install 'ntbox' from GitHub:
  (convertido del aviso) cannot remove prior installation of package ‘glue’

I have tried several times, uninstalling and installing devtools again as well as re-downloading the updates from devtools :: install_github ("luismurao / ntbox")

I always get the same error, and it keeps changing the package whose "cannot remove prior installation".

Any way to solve it?
Thanks!
