### ISSUE TITLE
GBIF Crash

### ISSUE THREAD

**Issue by loganwhiles** [luismurao/ntbox#5]
Hi Luis,

Awesome package! Thank you! 
So, I keep having an issue with the GUI suddenly disappearing after I select the "Search GBIF" button. I'm left looking back at RStudio with my console still running and several error codes repeated. I haven't used ntbox extensively, but I have worked past this point several times until recently. The error occurs regardless of species. I should note I'm fairly novice at R, so I apologize if the error is coming from my end. 

Below is what I see in the console after the crash, with the final warning (and 94: - 1: lines) repeated about 15 times. 

Warning in setDT(ans) :
  Some columns are a multi-column type (such as a matrix column): [47]. setDT will retain these columns as-is but subsequent operations like grouping and joining may fail. Please consider as.data.table() instead which will create a new column for each embedded column.
Warning: gbif: No records returned in GBIF for Ambystoma tigrinum
Warning: gbif: Column 47 of item 1 is length 3 inconsistent with column 1 which is length 300. Only length-1 columns are recycled.
Warning: Error in [[<-.data.frame: replacement has 2 rows, data has 0
  94: stop
  93: [[<-.data.frame
  91: ntbox::searh_gbif_data
  90: eventReactiveHandler [server_funcs/data_gbif.R#15]
  46: data_gbif_search
  45: <observer> [server_funcs/data_gbif.R#38]
   2: shiny::runApp
   1: ntbox::run_ntbox

I appreciate any advice you're able to offer.
-Logan

**Comment by luismurao** [comment]
Dear @loganwhiles ,
Could you install the new version of "rgbif" and the reload ntbox
```r
install.packages("rgbif")
library(ntbox)
run_ntbox()
```
The solution was posted [here](https://github.com/ropensci/spocc/issues/236#issuecomment-718887413).
Please let me know if it works for you 
Luis
