### ISSUE TITLE
Problems installing ntbox

### ISSUE THREAD

**Issue by GuguYanez** [luismurao/ntbox#7]
Hi! I have the same second problem of @Anil-2009 (Close Issue)

I follow all the steps and get:

Error: Failed to install 'ntbox' from GitHub:
(convertido del aviso) cannot remove prior installation of package ‘glue’

I have tried several times, uninstalling and installing devtools again as well as re-downloading the updates from devtools :: install_github ("luismurao / ntbox")

I always get the same error, and it keeps changing the package whose "cannot remove prior installation".

Then, I tried to install the package that R indicates to me as problematic (eg. "glue") and once installed, install ntbox. But I get the following error:

Warning in install.packages :
  package ‘ntbox’ is not available (for R version 4.0.2)

The problem is that ntbox does not work for R 4.0.2? Or is there another problem?

Any way to solve it?
Thanks!

**Comment by luismurao** [comment]
Hello @GuguYanez,
Could try to remove the "glue" package and then reinstall "ntbox". To remove the package you can just delete the folder of the package; type the following command in the R session if you don't know where is it
.libPaths()
Once deleted restart your R session and run:
devtools::install_github("luismurao/ntbox")

**Comment by GuguYanez** [comment]
Thank you very much! It worked! :)
