### ISSUE TITLE
Failed ntbox installation

### ISSUE THREAD

**Issue by gapz01** [luismurao/ntbox#8]
Hello

I've tried to install ntbox following all the package installation notes, but the following error appears (after skipping updates when asked)

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'ellipsis' 0.3.1 is being loaded, but >= 0.3.2 is required
Calls: <Anonymous> ... asNamespace -> loadNamespace -> namespaceImport -> loadNamespace
Ejecución interrumpida
ERROR: lazy loading failed for package 'ntbox'
* removing 'C:/Users/mipc/Documents/R/win-library/4.0/ntbox'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/mipc/AppData/Local/Temp/RtmpohVhH2/filef1445bf4226/ntbox_0.6.4.5.tar.gz’ had non-zero exit status

How could I solve it?
Thanks

**Comment by luismurao** [comment]
Hello @gapz01 ,
Could try to remove the "ellipsis" package and then reinstall "ntbox". To remove the package you can just delete the folder of the package; type the following command in the R session if you don't know where is it
.libPaths()
Once deleted restart your R session and run:
install.packages("ellipsis")
devtools::install_github("luismurao/ntbox")
You may get other errors like this one, but the recipe is the same check which package is cannot be updated by R, remove it and reinstall it. The following lines will tell you the messy package
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
namespace '**ellipsis**' 
I hope this helps
Luis
